repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-toml
      - id: check-json

  - repo: local
    hooks:
      - id: format-and-lint
        name: Format and Lint Python Code
        entry: bash
        args:
          - -c
          - |
            # Activate virtual environment
            source venv/bin/activate 2>/dev/null || source .venv/bin/activate 2>/dev/null || true

            # Run Black to format code
            echo "🔧 Running Black formatter..."
            black --line-length=88 src/ tests/ 2>/dev/null || true

            # Run Ruff to fix issues
            echo "🔧 Running Ruff linter with auto-fix..."
            ruff check --fix src/ tests/ 2>/dev/null || true

            # Run Ruff format
            echo "🔧 Running Ruff formatter..."
            ruff format src/ tests/ 2>/dev/null || true

            # Stage any files that were modified
            git add -u 2>/dev/null || true

            echo "✅ Code formatting and linting completed"
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: bootstrap-check
        name: Bootstrap Dependencies Check
        entry: bash
        args:
          - -c
          - |
            source venv/bin/activate 2>/dev/null || source .venv/bin/activate 2>/dev/null || true
            python -c "
            import sys
            try:
                from src.hermezos.config import Config
                from src.hermezos.index import make_index
                print('✓ Core HermezOS functionality available')

                try:
                    import requests
                    print('✓ requests available')
                except ImportError:
                    print('ℹ requests not available (optional)')

                try:
                    import kuzu
                    print('✓ kuzu available')
                except ImportError:
                    print('ℹ kuzu not available (optional)')

            except Exception as e:
                print(f'✗ Bootstrap check failed: {e}')
                sys.exit(1)
            "
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest-bootstrap
        name: Bootstrap Tests
        entry: bash
        args:
          - -c
          - |
            source venv/bin/activate 2>/dev/null || source .venv/bin/activate 2>/dev/null || true
            python -m pytest tests/test_bootstrap.py tests/test_index_null.py -v --tb=short
        language: system
        pass_filenames: false
        always_run: true
